# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkXLSpSbknni4Fbyh-kT5LsNXMA0oS0m
"""

import tensorflow as tf
import numpy as np

# mang 1 chieus
# cách 1
# tạo list
my_list =[1,9,15,39]
print("python list",my_list)
# chuyển lits --> numpy array
my_numpy_array= np.array(my_list)
print("numpy array", my_numpy_array)

# cách 2
a = np.array([1,9,15,39])
print(a)

# mang 2 chieu
c= np.array([(1,2,3),(4,5,6)])
print(c)
print(c.shape)
print(c.dtype)

# mang 3 chieu
d = np.array([
            [[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10.,11.,12.]]
          ])
print(d)
print(d.shape)

# tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros((2,2))
f = np.ones((3,3))
print('Zero matrix:\n',e)
print('one matrix\n',f)

# Reshape
e = np.array([[1.,2.,3.],[4.,5.,6.]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10.,11.,12.]]
            ])
print(g)
print(g.shape)
h=g.reshape(3,4)
print("reshape (3,4)\n",h)
j=g.reshape(3,2,2)
print("reshape (3,2,2)\n",j)
k=g.reshape(2,3,2)
print("reshape (2,3,2)\n",k)

#platten
e=np.array([[1.,2.,3.],[4.,5.,6.]])
f=e.flatten()
print(f)
g=np.array([[[1.,2.,3.],[4.,5.,6.]],
            [[7.,8.,9.],[10.,11.,12.]]
             ])
j=g.flatten()
print(j)

#4.6 hstack và vstack
f=np.array([1.,2.,3.])
g=np.array([4.,5.,6.])
h_stack=np.hstack((f,g))
print('Horizontal Append\n',h_stack)
v_stack=np.vstack((f,g))
print('Vertical Append\n',v_stack)

#4.7
a=np.random.randint(100,size=(5,))
print("Random 1-D aray\n",a)
b=np.random.randint(100,size=(3,4))
print("Random 2-D aray\n",b)
c=np.random.randint(100,size=(3,4,3))
print("Random 3-D aray\n",c)

#4.7.2
# sinh ngẫu nhiên mảng số thực [0,1]
a = np.random.rand(5)
print('Random 1-D array\n',a)
b=np.random.rand(3,4)
print('Random 2-D array\n',b)
c=np.random.rand(3,4,3)
print('Random 3-D array\n',c)

#4.7.3
a= np.random.normal(5,0.5,10)
print(a)

#4.7.4
# sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a=np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)
b =np.random.choice([2,4,6,8,10,12,14,16,18,20],size =(3,5))
print(b)

#4.8
A=np.matrix(np.ones((5,5)))
print("the matrix\n",A)
np.array(A)[2]=2
print("change values of third row with array\n",A)
np.asarray(A)[2]=2
print("change values of third row with asarray\n",A)